{
 "title": "AWS FSx - FSxn-CloudWatch",
 "tags": [
  "AWS",
  "CloudWatch",
  "FSxn",
  "Ontap"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "filesystemid",
    "label": "FileSystemId",
    "query": {}
   },
   {
    "name": "volumeid",
    "label": "VolumeId",
    "query": {}
   },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" }
  ]
 },
 "panels": [
  {
   "title": "FSxONTAP - FileSystem - Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available primary storage capacity",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dimensions": { "DataType": "All", "FileSystemId": "$filesystemid", "StorageTier": "SSD" },
       "id": "m1",
       "metricName": "StorageCapacity",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "DataType": "All", "FileSystemId": "$filesystemid", "StorageTier": "SSD" },
       "id": "m2",
       "metricName": "StorageUsed",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "expression": "(m1-m2)/PERIOD(m1)*$period",
       "id": "m3",
       "label": "AvailablePrimaryStorageCapacity",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Total client throughput (bytes/sec)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m1",
       "metricName": "DataReadBytes",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m2",
       "metricName": "DataWriteBytes",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "expression": "SUM(METRICS())/PERIOD(m1)",
       "id": "m3",
       "label": "TotalClientThroughput",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Total client IOPS (operations/sec)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m1",
       "metricName": "DataReadOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m2",
       "metricName": "DataWriteOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m3",
       "metricName": "MetadataOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "expression": "SUM(METRICS())/PERIOD(m1)",
       "id": "m4",
       "label": "TotalClientIOPS",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Storage distribution",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dimensions": { "DataType": "All", "FileSystemId": "$filesystemid", "StorageTier": "SSD" },
       "id": "m1",
       "label": "StorageCapacity",
       "metricName": "StorageCapacity",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "dimensions": { "DataType": "All", "FileSystemId": "$filesystemid", "StorageTier": "StandardCapacityPool" },
       "id": "m2",
       "label": "Capacity pool tier",
       "metricName": "StorageUsed",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "dimensions": { "DataType": "All", "FileSystemId": "$filesystemid", "StorageTier": "SSD" },
       "id": "m3",
       "label": "Primary tier - used",
       "metricName": "StorageUsed",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "expression": "(m1-m3)",
       "id": "m4",
       "label": "Primary tier - available",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "us-east-2",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Average latency (ms/operation)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 17, "x": 7, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m1",
       "metricName": "DataWriteOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m2",
       "metricName": "DataWriteOperationTime",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m3",
       "metricName": "DataReadOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m4",
       "metricName": "DataReadOperationTime",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m5",
       "metricName": "MetadataOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m6",
       "metricName": "MetadataOperationTime",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "expression": "1000 * m2/(m1+0.000001)",
       "id": "m7",
       "label": "Write operations",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "expression": "1000 * m4/(m3+0.000001)",
       "id": "m8",
       "label": "Read operations",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "expression": "1000 * m6/(m5+0.000001)",
       "id": "m9",
       "label": "Metadata operations",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Storage efficiency savings",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m1",
       "metricName": "StorageEfficiencySavings",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m2",
       "metricName": "StorageUsed",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "expression": "m1",
       "id": "m3",
       "label": "Space savings",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "expression": "100*(m1/(m1+m2))",
       "id": "m4",
       "label": "Space savings (%)",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "FSxONTAP - FileSystem - Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available primary storage capacity (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "dimensions": { "DataType": "All", "FileSystemId": "$filesystemid", "StorageTier": "SSD" },
       "id": "m1",
       "metricName": "StorageCapacity",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "id": "m2",
       "metricName": "StorageUsed",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "expression": "(m1-m2)/PERIOD(m1)*$period",
       "label": "Available primary storage capacity (bytes)",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Primary storage capacity utilization (percent)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "DataType": "All", "FileSystemId": "$filesystemid", "StorageTier": "SSD" },
       "id": "m1",
       "metricName": "StorageUsed",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "DataType": "All", "FileSystemId": "$filesystemid", "StorageTier": "SSD" },
       "id": "m2",
       "metricName": "StorageCapacity",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "expression": "100 * m1/(m2+0.000001)",
       "label": "Primary storage capacity utilization",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "FSxONTAP - FileSystem - Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk throughput - burst balance (percent)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 3 },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "metricName": "FileServerDiskThroughputBalance",
       "namespace": "AWS/FSx",
       "period": "300",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Cache hit ratio (percent)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 10, "y": 3 },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "metricName": "FileServerCacheHitRatio",
       "namespace": "AWS/FSx",
       "period": "60",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "CPU utilization (percent)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 11 },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "metricName": "CPUUtilization",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Disk throughput - utilization (percent)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 10, "y": 11 },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "metricName": "FileServerDiskThroughputUtilization",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Disk IOPS - burst balance (percent)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "metricName": "FileServerDiskIopsBalance",
       "namespace": "AWS/FSx",
       "period": "300",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Disk IOPS - utilization (percent)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 10, "y": 19 },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "metricName": "FileServerDiskIopsUtilization",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Network throughput - utilization (percent)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 26 },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid" },
       "metricName": "NetworkThroughputUtilization",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "FSxONTAP - FileSystem - Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available storage capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m1",
       "metricName": "StorageCapacity",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m2",
       "metricName": "StorageUsed",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "DataType": "All", "FileSystemId": "$filesystemid", "StorageTier": "SSD" },
       "id": "m3",
       "label": "All SSD StorageCapacity",
       "metricName": "StorageCapacity",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "DataType": "All", "FileSystemId": "$filesystemid", "StorageTier": "SSD" },
       "id": "m4",
       "label": "All SSD StorageCapacity",
       "metricName": "StorageUsed",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "expression": "MIN([m1-m2, m3-m4])/PERIOD(m1)*$period",
       "id": "m5",
       "label": "Available storage capacity",
       "metricEditorMode": 1,
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Total client throughput (bytes/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m1",
       "metricName": "DataReadBytes",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m2",
       "metricName": "DataWriteBytes",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "expression": "SUM(METRICS())/PERIOD(m1)",
       "id": "m3",
       "label": "Total client throughput",
       "metricEditorMode": 1,
       "namespace": "AWS/EFS",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Storage distribution",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dimensions": { "DataType": "Other", "FileSystemId": "$filesystemid", "StorageTier": "All", "VolumeId": "$volumeid" },
       "id": "m5",
       "label": "Other data",
       "metricName": "StorageUsed",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "dimensions": { "DataType": "Snapshot", "FileSystemId": "$filesystemid", "StorageTier": "All", "VolumeId": "$volumeid" },
       "id": "m6",
       "label": "Snapshot data",
       "metricName": "StorageUsed",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "dimensions": { "DataType": "User", "FileSystemId": "$filesystemid", "StorageTier": "All", "VolumeId": "$volumeid" },
       "id": "m7",
       "label": "User data",
       "metricName": "StorageUsed",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "expression": "MIN([m1-m2, m3-m4])/PERIOD(m1)*60",
       "id": "m8",
       "label": "Available volume capacity",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Total client IOPS (operations/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m1",
       "metricName": "DataReadOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m2",
       "metricName": "DataWriteOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m3",
       "metricName": "MetadataOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "expression": "SUM(METRICS())/PERIOD(m1)",
       "id": "m4",
       "label": "Total client IOPS",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Available files (inodes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m1",
       "metricName": "FilesCapacity",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m2",
       "metricName": "FilesUsed",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "expression": "(m1-m2)/PERIOD(m1)*60",
       "id": "m3",
       "label": "Available files (inodes)",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Average latency (ms/operation)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m1",
       "metricName": "DataWriteOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m2",
       "metricName": "DataWriteOperationTime",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m3",
       "metricName": "DataReadOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m4",
       "metricName": "DataReadOperationTime",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m5",
       "metricName": "MetadataOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m6",
       "metricName": "MetadataOperationTime",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "expression": "1000 * m2/(m1+0.000001)",
       "id": "m7",
       "label": "Write operations",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "expression": "1000 * m4/(m3+0.000001)",
       "id": "m8",
       "label": "Read operations",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "expression": "1000 * m6/(m5+0.000001)",
       "id": "m9",
       "label": "Metadata operations",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Capacity Pool IOPS (operations/sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m1",
       "metricName": "CapacityPoolReadOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "dimensions": { "FileSystemId": "$filesystemid", "VolumeId": "$volumeid" },
       "id": "m2",
       "metricName": "CapacityPoolWriteOperations",
       "namespace": "AWS/FSx",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      },
      {
       "expression": "m1/PERIOD(m1)",
       "id": "m3",
       "label": "Capacity Pool Read Operations (operations/sec)",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      },
      {
       "expression": "m2/PERIOD(m2)",
       "id": "m4",
       "label": "Capacity Pool Write Operations (operations/sec)",
       "metricEditorMode": 1,
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "For more information, see [Amazon CloudWatch Metrics for Amazon FSx ONTAP](https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/monitoring-cloudwatch.html)."
   }
  }
 ]
}